// ************************************************************************************************************************
// Created By:  Password's Team
// Worksheet:   Copy Data Tables Snowflake
// Usage:       This worksheet is used to Copy Data from CSV into Tables
// ************************************************************************************************************************

// Gold Data Schema
USE ROLE ACCOUNTADMIN;
USE DATABASE LOGISTICS;
USE SCHEMA GOLD_DATA;

// Maintenance Check File Format + Copy Into Tables
CREATE OR REPLACE TEMP FILE FORMAT MAINTENANCE_CHECK
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO LOGISTICS.GOLD_DATA.MAINTENANCE_CHECK
FROM @CSV_FILES/maintenance_check.csv
FILE_FORMAT = (FORMAT_NAME = 'MAINTENANCE_CHECK');


// Maintenance Logs File Format + Copy Into Tables
CREATE OR REPLACE TEMP FILE FORMAT MAINTENANCE_LOGS
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO LOGISTICS.GOLD_DATA.MAINTENANCE_LOGS
FROM @CSV_FILES/maintenance_logs.csv
FILE_FORMAT = (FORMAT_NAME = 'MAINTENANCE_LOGS');


// Weather Forecast File Format + Copy Into Tables
CREATE OR REPLACE TEMP FILE FORMAT WEATHER_OBSERVATION
    TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO LOGISTICS.GOLD_DATA.WEATHER_OBSERVATION
FROM @CSV_FILES/weather_observation.csv
FILE_FORMAT = (FORMAT_NAME = 'WEATHER_OBSERVATION');


// Customer Complaints File Format + Copy Into Tables
CREATE OR REPLACE TEMP FILE FORMAT CUSTOMER_COMPLAINTS
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO LOGISTICS.GOLD_DATA.CUSTOMER_COMPLAINTS
FROM @CSV_FILES/customer_complaints.csv
FILE_FORMAT = (FORMAT_NAME = 'CUSTOMER_COMPLAINTS');


// Financial Expenditure File Format + Copy Into Tables
CREATE OR REPLACE TEMP FILE FORMAT FINANCIAL_EXPENDITURE
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO LOGISTICS.GOLD_DATA.FINANCIAL_EXPENDITURE
FROM @CSV_FILES/financial_expenditure.csv
FILE_FORMAT = (FORMAT_NAME = 'FINANCIAL_EXPENDITURE');


// Fuel Cost Logs File Format + Copy Into Tables
CREATE OR REPLACE TEMP FILE FORMAT FUEL_COST_LOGS
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO LOGISTICS.GOLD_DATA.FUEL_COST_LOGS
FROM @CSV_FILES/fuel_cost_logs.csv
FILE_FORMAT = (FORMAT_NAME = 'FUEL_COST_LOGS');


// IOT Telemetry File Format + Copy Into Tables
CREATE OR REPLACE TEMP FILE FORMAT IOT_TELEMETRY
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO LOGISTICS.GOLD_DATA.IOT_TELEMETRY
FROM @CSV_FILES/iot_telemetry.csv
FILE_FORMAT = (FORMAT_NAME = 'IOT_TELEMETRY');


// Shipment Schedule File Format + Copy Into Tables
CREATE OR REPLACE TEMP FILE FORMAT SHIPMENT_SCHEDULE
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO LOGISTICS.GOLD_DATA.SHIPMENT_SCHEDULE
FROM @CSV_FILES/shipment_schedule.csv
FILE_FORMAT = (FORMAT_NAME = 'SHIPMENT_SCHEDULE');


// ************************************************************************************************************************
// Silver Data Schema
USE ROLE ACCOUNTADMIN;
USE DATABASE LOGISTICS;
USE SCHEMA SILVER_DATA;


// Weather Forecast Raw File Format + Copy Into Tables
CREATE OR REPLACE TEMP FILE FORMAT WEATHER_FORECAST
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO;

COPY INTO LOGISTICS.SILVER_DATA.WEATHER_FORECAST_RAW
FROM @CSV_FILES/weather_forecast.csv
FILE_FORMAT = (FORMAT_NAME = 'WEATHER_FORECAST');